[package]
name = "micdeck-dsp"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["staticlib"]

[dependencies]
aec3 = "0.3.1"
nnnoiseless = { version = "0.5.2", default-features = false }

[profile.release]
codegen-units = 1
lto = "thin"
opt-level = 3
panic = "abort"
strip = "symbols"
